### ISSUE TITLE
Option to add custom URLs (+ Macy's URL incorrect)

### ISSUE THREAD

**Issue by rogersheu** [corbindavenport/wii-shop-extension#12]
Nifty extension!

1a. Incorporating a UI to add your own URLs to the site list would be useful, especially if a user shops a lot on a page that's not already in the site list. 

1b. Alternatively, maybe the script can search the source code for a cart container, since most shopping sites have a cart, and then play the music if it finds it.

2. If neither 1a or 1b are implemented, it'd make sense to manually expand the list to websites people shop on, such as clothing, house decor, home improvement, sports, and more.

More generally, ```craigslist.com``` and Facebook marketplace may be appropriate sites to include. Any of Reddit's deals/sales sites might be worth including as well.

Note: Also, in ```site-list.js```, ```macys.com``` has a typo.

**Comment by corbindavenport** [comment]
Thanks for catching the typo, I've just fixed that. Craigslist might be difficult to add because it has lots of subdomains that all need to be specified.

Automatic detection would probably be too tricky to implement without a high mismatch rate, but I do plan on adding a way to add your own sites. That's covered in #8, so I'll close this as a duplicate.

**Comment by rogersheu** [comment]
Thanks for the quick response! By the way, your extension was mentioned on Reddit [here](https://www.reddit.com/r/AskReddit/comments/r2q1i2/which_song_is_in_your_opinion_100_perfect/), which is how I found it.

**Comment by corbindavenport** [comment]
Hah, that's pretty funny. I've seen a slow uptick in people joining the Discord server, maybe that's where it's from.
