### ISSUE TITLE
Not working on kiwi browser

### ISSUE THREAD

**Issue by soccerboys2008** [corbindavenport/wii-shop-extension#42]
Tried it on kiwi browser (for extension support on mobile device) and can't seem to get it to work. I know this is a bit of a edge case, but I do do most of my shopping from mobile browser

Works great on chromium on linux

**Comment by corbindavenport** [comment]
Kiwi Browser doesn't offer any developer documentation for its implementation of the extension API, and because Android has different rules for music playback, this might be impossible to fix entirely. It's also possible the switch to Manifest V3 (#7) might change something, since the music playback code might have to be rewritten.

I'll accept pull requests if anyone can fix this, but I'm not sure where to start myself.
